name: Build aarch64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: latest
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Build
        run: zig build --sysroot "$(xcrun --sdk iphoneos --show-sdk-path)" -Dtarget=aarch64-ios
